spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql:
   init:
     mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: root
    password: root

server.port: 8080

logging.level.org.springframework.orm.jpa: INFO
logging.level.org.springframework.transaction: INFO
logging.level.org.springframework.transaction.interceptor: TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager: DEBUG



